name: 'Publish pre-release'
on:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Check if next-version.txt exists
      run: |
        if [ -f ./publish_workflow_payload/next-version.txt ]; then
          echo "File exists!"
        else
          echo "File not found!"
        fi
