name: 'Publish pre-release'
on:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package_name
          path: ./publish_workflow_payload/package_name.txt
