name: 'Publish pre-release'
on:
  workflow_dispatch:

jobs:
  create-files-and-upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory publish_workflow_payload
        run: |
          mkdir -p publish_workflow_payload

      - name: Create next-version.txt and add content
        run: |
          echo "testnextverison" > publish_workflow_payload/next-version.txt

      - name: Create package-name.txt and add content
        run: |
          echo "testpackagename" > publish_workflow_payload/package-name.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish_workflow_payload
          path: publish_workflow_payload
          
      - name: Output run-id
        run: |
          echo "Run ID: ${{ github.run_id }}"
