name: 'Publish release'
on:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish_workflow_payload
          path: publish_workflow_payload/
