name: 'Publish pre-release'
on:
  workflow_dispatch:

jobs:
  create-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create nextversion
        run: |
          mkdir -p publish_workflow_payload
          echo "testnextversion" > publish_workflow_payload/next-version.txt

     
      # Шаг 3: Загружаем файл как артефакт
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish_workflow_payload
          path: ./publish_workflow_payload/next-version.txt
